package com.example.statussaver

object Strings {
    private val translations = mapOf(
        "English" to mapOf(
            "app_title" to "Status Saver",
            "splash_subtitle" to "Save statuses instantly",
            "click_to_start" to "Click to Start",
            "terms_agree" to "By proceeding you agree to Terms & Privacy Policy",
            "language" to "Language",
            "lang_subtitle" to "The language can be changed later in Settings.",
            "allow_storage_access" to "Allow storage access",
            "allow_access_desc" to "We need access to your device storage to find and save save statuses.",
            "allow_access_btn" to "Allow access",
            "not_now" to "Not now",
            "status_tab" to "Status",
            "b_status_tab" to "B Status",
            "saved_tab" to "Saved",
            "setting_tab" to "Setting",
            "no_statuses_found" to "No statuses found",
            "no_statuses_saved" to "No statuses save",
            "empty_subtitle" to "Open WhatsApp and view a status to see it here.",
            "saved_successfully" to "Saved successfully!",
            "storage_folder_access" to "Storage Folder Access",
            "privacy_policy" to "Privacy Policy",
            "settings" to "Settings"
        ),
        "العربية" to mapOf(
            "app_title" to "موفر الحالة",
            "splash_subtitle" to "حفظ الحالات فوراً",
            "click_to_start" to "انقر للبدء",
            "terms_agree" to "بالمتابعة فإنك توافق على الشروط وسياسة الخصوصية",
            "language" to "اللغة",
            "lang_subtitle" to "يمكن تغيير اللغة لاحقاً من الإعدادات.",
            "allow_storage_access" to "السماح بالوصول للتخزين",
            "allow_access_desc" to "نحتاج إلى الوصول إلى ذاكرة الجهاز للعثور على الحالات وحفظها.",
            "allow_access_btn" to "السماح بالوصول",
            "not_now" to "ليس الآن",
            "status_tab" to "الحالة",
            "b_status_tab" to "أعمال الحالة",
            "saved_tab" to "المحفوظات",
            "setting_tab" to "الإعدادات",
            "no_statuses_found" to "لم يتم العثور على حالات",
            "no_statuses_saved" to "لا توجد حالات محفوظة",
            "empty_subtitle" to "افتح واتساب وشاهد حالة لكي تظهر هنا.",
            "saved_successfully" to "تم الحفظ بنجاح!",
            "storage_folder_access" to "وصول مجلد التخزين",
            "privacy_policy" to "سياسة الخصوصية",
            "settings" to "الإعدادات"
        ),
        "فارسی" to mapOf(
            "app_title" to "ذخیره‌کننده وضعیت",
            "splash_subtitle" to "ذخیره فوری وضعیت‌ها",
            "click_to_start" to "برای شروع کلیک کنید",
            "terms_agree" to "با ادامه، شما با شرایط و حریم خصوصی موافقید",
            "language" to "زبان",
            "lang_subtitle" to "زبان را می‌توان بعداً در تنظیمات تغییر داد.",
            "allow_storage_access" to "اجازه دسترسی به حافظه",
            "allow_access_desc" to "ما برای یافتن و ذخیره وضعیت‌ها به دسترسی حافظه نیاز داریم.",
            "allow_access_btn" to "اجازه دسترسی",
            "not_now" to "الان نه",
            "status_tab" to "وضعیت",
            "b_status_tab" to "وضعیت تجاری",
            "saved_tab" to "ذخیره شده",
            "setting_tab" to "تنظیمات",
            "no_statuses_found" to "هیچ وضعیتی یافت نشد",
            "no_statuses_saved" to "هیچ وضعیتی ذخیره نشده",
            "empty_subtitle" to "واتساپ را باز کنید و یک وضعیت را ببینید.",
            "saved_successfully" to "با موفقیت ذخیره شد!",
            "storage_folder_access" to "دسترسی به پوشه حافظه",
            "privacy_policy" to "حریم خصوصی",
            "settings" to "تنظیمات"
        ),
        "Deutsch" to mapOf(
            "app_title" to "Status Saver",
            "splash_subtitle" to "Statuses sofort speichern",
            "click_to_start" to "Klick zum Starten",
            "terms_agree" to "Mit dem Fortfahren stimmen Sie den Bedingungen zu",
            "language" to "Sprache",
            "lang_subtitle" to "Die Sprache kann später geändert werden.",
            "allow_storage_access" to "Speicherzugriff erlauben",
            "allow_access_desc" to "Wir benötigen Zugriff auf den Speicher, um Statuses zu speichern.",
            "allow_access_btn" to "Zugriff erlauben",
            "not_now" to "Nicht jetzt",
            "status_tab" to "Status",
            "b_status_tab" to "B-Status",
            "saved_tab" to "Gespeichert",
            "setting_tab" to "Einstellung",
            "no_statuses_found" to "Keine Statuses gefunden",
            "no_statuses_saved" to "Keine Statuses gespeichert",
            "empty_subtitle" to "Öffnen Sie WhatsApp und sehen Sie sich einen Status an.",
            "saved_successfully" to "Erfolgreich gespeichert!",
            "storage_folder_access" to "Speicherordner-Zugriff",
            "privacy_policy" to "Datenschutzrichtlinie",
            "settings" to "Einstellungen"
        ),
        "Espanol" to mapOf(
            "app_title" to "Guardador de Estado",
            "splash_subtitle" to "Guardar estados al instante",
            "click_to_start" to "Haz clic para empezar",
            "terms_agree" to "Al proceder aceptas Términos y Privacidad",
            "language" to "Idioma",
            "lang_subtitle" to "El idioma se puede cambiar más tarde en Ajustes.",
            "allow_storage_access" to "Permitir acceso al almacenamiento",
            "allow_access_desc" to "Necesitamos acceso al almacenamiento para guardar estados.",
            "allow_access_btn" to "Permitir acceso",
            "not_now" to "Ahora no",
            "status_tab" to "Estado",
            "b_status_tab" to "Estado B",
            "saved_tab" to "Guardados",
            "setting_tab" to "Ajuste",
            "no_statuses_found" to "No se encontraron estados",
            "no_statuses_saved" to "No hay estados guardados",
            "empty_subtitle" to "Abre WhatsApp y mira un estado para verlo aquí.",
            "saved_successfully" to "¡Guardado con éxito!",
            "storage_folder_access" to "Acceso a Carpeta",
            "privacy_policy" to "Política de Privacidad",
            "settings" to "Ajustes"
        ),
        "Indonesi" to mapOf(
            "app_title" to "Penghemat Status",
            "splash_subtitle" to "Simpan status secara instan",
            "click_to_start" to "Klik untuk Memulai",
            "terms_agree" to "Dengan melanjutkan Anda menyetujui Syarat & Privasi",
            "language" to "Bahasa",
            "lang_subtitle" to "Bahasa dapat diubah nanti di Pengaturan.",
            "allow_storage_access" to "Izinkan akses penyimpanan",
            "allow_access_desc" to "Kami memerlukan akses penyimpanan untuk menyimpan status.",
            "allow_access_btn" to "Izinkan Akses",
            "not_now" to "Nanti saja",
            "status_tab" to "Status",
            "b_status_tab" to "Status B",
            "saved_tab" to "Tersimpan",
            "setting_tab" to "Pengaturan",
            "no_statuses_found" to "Tidak ada status ditemukan",
            "no_statuses_saved" to "Tidak ada status tersimpan",
            "empty_subtitle" to "Buka WhatsApp dan lihat status untuk melihatnya di sini.",
            "saved_successfully" to "Berhasil disimpan!",
            "storage_folder_access" to "Akses Folder Penyimpanan",
            "privacy_policy" to "Kebijakan Privasi",
            "settings" to "Pengaturan"
        ),
        "Urdu" to mapOf(
            "app_title" to "اسٹیٹس سیور",
            "splash_subtitle" to "اسٹیٹس فوراً محفوظ کریں",
            "click_to_start" to "شروع کرنے کے لیے کلک کریں",
            "terms_agree" to "آگے بڑھ کر آپ شرائط و ضوابط سے متفق ہوتے ہیں",
            "language" to "زبان",
            "lang_subtitle" to "زبان بعد میں سیٹنگز میں بھی تبدیل کی جا سکتی ہے۔",
            "allow_storage_access" to "اسٹوریج تک رسائی کی اجازت دیں",
            "allow_access_desc" to "ہمیں اسٹیٹس تلاش اور محفوظ کرنے کے لیے اسٹوریج رسائی درکار ہے۔",
            "allow_access_btn" to "رسائی کی اجازت دیں",
            "not_now" to "ابھی نہیں",
            "status_tab" to "اسٹیٹس",
            "b_status_tab" to "بزنس اسٹیٹس",
            "saved_tab" to "محفوظ شدہ",
            "setting_tab" to "سیٹنگز",
            "no_statuses_found" to "کوئی اسٹیٹس نہیں ملا",
            "no_statuses_saved" to "کوئی اسٹیٹس محفوظ نہیں ہے",
            "empty_subtitle" to "واٹس ایپ کھولیں اور اسٹیٹس دیکھیں تاکہ وہ یہاں ظاہر ہو۔",
            "saved_successfully" to "کامیابی سے محفوظ ہو گیا!",
            "storage_folder_access" to "اسٹوریج فولڈر رسائی",
            "privacy_policy" to "پرائیویسی پالیسی",
            "settings" to "سیٹنگز"
        )
    )

    fun get(key: String, language: String): String {
        return translations[language]?.get(key) ?: translations["English"]?.get(key) ?: key
    }
}
